const KEY = 'TITLE';

const UPDATE_FILTER = `[${KEY}] UPDATE FILTER`;
const RESET_FILTER = `[${KEY}] RESET FILTER`;

const UPDATE_TITLES = `[${KEY}] UPDATE TITLES`;
const CLEAR_TITLES = `[${KEY}] CLEAR TITLES`;

export default {
    KEY,
    UPDATE_FILTER,
    RESET_FILTER,
    UPDATE_TITLES,
    CLEAR_TITLES
}